version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advantage-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EXPO_PUBLIC_SUPABASE_URL=${EXPO_PUBLIC_SUPABASE_URL}
      - EXPO_PUBLIC_SUPABASE_ANON_KEY=${EXPO_PUBLIC_SUPABASE_ANON_KEY}
      - EXPO_PUBLIC_GOOGLE_MAPS_API_KEY=${EXPO_PUBLIC_GOOGLE_MAPS_API_KEY}
      - EXPO_PUBLIC_GOOGLE_GEMINI_API_KEY=${EXPO_PUBLIC_GOOGLE_GEMINI_API_KEY}
    networks:
      - advantage-network
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: advantage-redis
    ports:
      - "6379:6379"
    networks:
      - advantage-network
    restart: unless-stopped
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: advantage-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - advantage-network
    restart: unless-stopped

networks:
  advantage-network:
    driver: bridge

volumes:
  redis_data:
    driver: local 